# install libvirt
- hosts: virthost
  become: true
  become_user: root
  roles:
   - role: ansible-role-libvirt-host
  tasks:
    - name: install required package
      dnf:
        name: [ "genisoimage", "jq" ]
        state: present

# install terraform under ./tf/
- hosts: virthost
  roles:
   - role: terraform_install

- hosts: virthost
  roles:
   - role: download_vm_image
