- hosts: virthost
  tasks:
    # cd tf; ./terraform destroy -auto-approve
    - name: tearing down vms
      terraform:
        project_path: "{{ ansible_env.HOME }}/tf"
        binary_path: "{{ ansible_env.HOME }}/tf/terraform"
        state: absent
