- hosts: virthost
  tasks:
    # cd tf; ./terraform destroy -auto-approve
    - name: tearing down vms
      terraform:
        project_path: "{{ terraform_work }}"
        binary_path: "{{ terraform_work }}/terraform"
        state: absent
