---
- name: crio install
  shell: |
    dnf -y copr enable rhcontainerbot/container-selinux;
    curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/Fedora_34/devel:kubic:libcontainers:stable.repo;
    curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}/Fedora_34/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}.repo;
    dnf -y install cri-o

- name: delete cni directory once
  file:
    path: /etc/cni/net.d
    state: absent
    owner: root
    group: root
    mode: 0755

- name: create work directory
  file:
    path: /etc/cni/net.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: enable systemd
  systemd:
    name: crio
    enabled: yes
    daemon_reload: yes
    state: started
