---
- name: delete work directory
  file:
    path: "{{ ansible_env.HOME }}/tf"
    state: absent
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: create work directory
  file:
    path: "{{ ansible_env.HOME }}/tf"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: install terraform binary
  unarchive:
    src: "{{ terraform_url }}"
    dest: "{{ ansible_env.HOME }}/tf"
    mode: 0755
    remote_src: yes

- name: create terraform libvirt provider directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/terraform/plugins/registry.terraform.io/dmacvicar/libvirt/0.6.3/linux_amd64"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: install terraform libvirt provider
  unarchive:
    src: "{{ terraform_libvirt_url }}"
    dest: "{{ ansible_env.HOME }}/.local/share/terraform/plugins/registry.terraform.io/dmacvicar/libvirt/0.6.3/linux_amd64"
    mode: 0755
    remote_src: yes
  when: not build_libvirt_provider

- name: Install golang and build deps on Fedora
  dnf:
    name: ['golang', 'libvirt', 'libvirt-devel']
    state: latest
  when: build_libvirt_provider

- name: create terraform libvirt provider source directory
  file:
    path: "/usr/src/terraform-provider-libvirt"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755
  when: build_libvirt_provider

- name: clone libvirt provider
  git:
    repo: https://github.com/dmacvicar/terraform-provider-libvirt.git
    dest: /usr/src/terraform-provider-libvirt
    depth: 1
    version: v0.6.3
  when: build_libvirt_provider

- name: build libvirt provider from source
  make:
    chdir: /usr/src/terraform-provider-libvirt
  when: build_libvirt_provider

- name: copy terraform-provider-libvirt binary into place.
  copy:
    src: "/usr/src/terraform-provider-libvirt/terraform-provider-libvirt"
    dest: "{{ ansible_env.HOME }}/.local/share/terraform/plugins/registry.terraform.io/dmacvicar/libvirt/0.6.3/linux_amd64/terraform-provider-libvirt"
    remote_src: true
    force: yes
  when: build_libvirt_provider


- name: create images directory
  file:
    path: "{{ ansible_env.HOME }}/tf/images"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: download vm base image
  get_url:
    url: "{{ vm_image_url }}"
    dest: "{{ ansible_env.HOME }}/tf/images/{{ vm_image_url | basename }}"
    checksum: "sha256:{{ vm_image_sha256 }}"

- name: resize vm image
  command: qemu-img resize "{{ ansible_env.HOME }}/tf/images/{{ vm_image_url | basename }}" 20G
