---
- name: delete work directory
  file:
    path: "{{ playbook_dir }}/tf"
    state: absent
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: create work directory
  file:
    path: "{{ playbook_dir }}/tf"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: install terraform binary
  unarchive:
    src: "{{ terraform_url }}"
    dest: "{{ playbook_dir }}/tf"
    mode: 0755
    remote_src: yes

- name: create terraform libvirt provider directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/terraform/plugins/registry.terraform.io/dmacvicar/libvirt/0.6.3/linux_amd64"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: install terraform libvirt provider
  unarchive:
    src: "{{ terraform_libvirt_url }}"
    dest: "{{ ansible_env.HOME }}/.local/share/terraform/plugins/registry.terraform.io/dmacvicar/libvirt/0.6.3/linux_amd64"
    mode: 0755
    remote_src: yes

- name: create images directory
  file:
    path: "{{ ansible_env.PWD }}/tf/images"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: download vm base image
  get_url:
    url: "{{ vm_image_url }}"
    dest: "{{ playbook_dir }}/tf/images/{{ vm_image_url | basename }}"
    checksum: "sha256:{{ vm_image_sha256 }}"

- name: resize vm image
  command: qemu-img resize "{{ playbook_dir }}/tf/images/{{ vm_image_url | basename }}" 20G
