---
- name: delete work directory
  file:
    path: "{{ terraform_workdir }}"
    state: absent
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: create work directory
  file:
    path: "{{ terraform_workdir }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: install terraform binary
  unarchive:
    src: "{{ terraform_url }}"
    dest: "{{ terraform_workdir }}"
    mode: 0755
    remote_src: yes

- name: create images directory
  file:
    path: "{{ terraform_workdir }}/images"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755

- name: download vm base image (with sha256)
  get_url:
    url: "{{ vm_image_url }}"
    dest: "{{ terraform_workdir }}/images/{{ vm_image_url | basename }}"
    checksum: "sha256:{{ vm_image_sha256 }}"
  when: vm_image_sha256 != "skip"

- name: download vm base image
  get_url:
    url: "{{ vm_image_url }}"
    dest: "{{ terraform_workdir }}/images/{{ vm_image_url | basename }}"
  when: vm_image_sha256 == "skip"

- name: resize vm image
  command: qemu-img resize "{{ terraform_workdir }}/images/{{ vm_image_url | basename }}" 20G
