# -------- Configure kubectl -------------
# It does the following
# sudo cp /etc/kubernetes/admin.conf $HOME/.kube
# sudo chown $(id -u):$(id -g) $HOME/.kube/admin.conf
# export KUBECONFIG=$HOME/.kube/admin.conf

- name: Ensure .kube folder exists
  file:
    path: "/home/{{ vm_image_user }}/.kube/"
    state: directory
    owner: "{{ vm_image_user }}"
    group: "{{ vm_image_user }}"
    mode: 0755

- name: Copy admin.conf to kubectl user's home
  shell: >
    cp -f /etc/kubernetes/admin.conf /home/{{ vm_image_user }}/.kube/admin.conf
  args:
    creates: "/home/{{ vm_image_user }}/.kube/admin.conf"

- name: Set admin.conf ownership
  file:
    path: "/home/{{ vm_image_user }}/.kube/admin.conf"
    owner: "{{ vm_image_user }}"
    group: "{{ vm_image_user }}"

- name: Add KUBECONFIG env for admin.conf to .bashrc
  lineinfile:
    dest: "/home/{{ vm_image_user }}/.bashrc"
    regexp: "KUBECONFIG"
    line: "export KUBECONFIG=/home/{{ vm_image_user }}/.kube/admin.conf"
